"""
blockchain_client.py - Web3 interface for Celo blockchain interaction

Handles:
- Prediction submission on-chain
- Agent wallet interactions
- x402 payment processing (simplified)
- Reading prediction data from chain
"""

import os
import logging
from typing import Optional, Dict, Any
from dataclasses import dataclass
from eth_account import Account
from web3 import Web3
from web3.contract import Contract
from web3.types import TxReceipt, HexStr

logger = logging.getLogger(__name__)

# Contract ABIs (simplified - full ABIs would be generated by Foundry)
PREDICTION_CONTRACT_ABI = [
    {
        "inputs": [
            {"name": "_predictionId", "type": "bytes32"},
            {"name": "_matchId", "type": "bytes32"},
            {"name": "_homeTeam", "type": "string"},
            {"name": "_awayTeam", "type": "string"},
            {"name": "_league", "type": "string"},
            {"name": "_prediction", "type": "uint8"},
            {"name": "_confidence", "type": "uint256"},
            {"name": "_matchDate", "type": "uint256"},
        ],
        "name": "submitPrediction",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_predictionId", "type": "bytes32"}],
        "name": "getPrediction",
        "outputs": [
            {
                "components": [
                    {"name": "predictionId", "type": "bytes32"},
                    {"name": "matchId", "type": "bytes32"},
                    {"name": "agent", "type": "address"},
                    {"name": "homeTeam", "type": "string"},
                    {"name": "awayTeam", "type": "string"},
                    {"name": "league", "type": "string"},
                    {"name": "prediction", "type": "uint8"},
                    {"name": "confidence", "type": "uint256"},
                    {"name": "timestamp", "type": "uint256"},
                    {"name": "matchDate", "type": "uint256"},
                    {"name": "resolved", "type": "bool"},
                    {"name": "outcome", "type": "uint8"},
                    {"name": "stakeAmount", "type": "uint256"},
                ],
                "name": "",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getAgentAccuracy",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"name": "", "type": "bytes32"}],
        "name": "predictions",
        "outputs": [
            {"name": "predictionId", "type": "bytes32"},
            {"name": "matchId", "type": "bytes32"},
            {"name": "agent", "type": "address"},
            {"name": "homeTeam", "type": "string"},
            {"name": "awayTeam", "type": "string"},
            {"name": "league", "type": "string"},
            {"name": "prediction", "type": "uint8"},
            {"name": "confidence", "type": "uint256"},
            {"name": "timestamp", "type": "uint256"},
            {"name": "matchDate", "type": "uint256"},
            {"name": "resolved", "type": "bool"},
            {"name": "outcome", "type": "uint8"},
            {"name": "stakeAmount", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "agentWallet",
        "outputs": [{"name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
]

AGENT_WALLET_ABI = [
    {
        "inputs": [
            {"name": "_predictionId", "type": "bytes32"},
            {"name": "_matchId", "type": "bytes32"},
            {"name": "_homeTeam", "type": "string"},
            {"name": "_awayTeam", "type": "string"},
            {"name": "_league", "type": "string"},
            {"name": "_prediction", "type": "uint8"},
            {"name": "_confidence", "type": "uint256"},
            {"name": "_matchDate", "type": "uint256"},
        ],
        "name": "submitPrediction",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_backend", "type": "address"}, {"name": "_authorized", "type": "bool"}],
        "name": "authorizeBackend",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"name": "_addr", "type": "address"}],
        "name": "isAuthorized",
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "predictionContract",
        "outputs": [{"name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
]


@dataclass
class PredictionResult:
    """Result from submitting prediction on-chain"""
    success: bool
    tx_hash: Optional[str] = None
    prediction_id: Optional[str] = None
    error: Optional[str] = None


class BlockchainClient:
    """
    Web3 client for Celo blockchain interactions.
    
    Handles:
    - Submitting predictions via agent wallet
    - Querying on-chain prediction data
    - Managing agent wallet interactions
    """

    def __init__(self):
        # Configuration from environment
        self.enabled = os.getenv("BLOCKCHAIN_ENABLED", "False").lower() == "true"
        self.rpc_url = os.getenv("CELO_RPC_URL", "https://alfajores-forno.celo-testnet.org")
        self.private_key = os.getenv("AGENT_PRIVATE_KEY", "")
        
        # Contract addresses
        self.agent_wallet_address = os.getenv("AGENT_WALLET", "")
        self.prediction_contract_address = os.getenv("PREDICTION_CONTRACT", "")
        self.agent_id = os.getenv("AGENT_ID", "")
        
        # Initialize Web3 if enabled
        self.w3: Optional[Web3] = None
        self.agent_wallet: Optional[Contract] = None
        self.prediction_contract: Optional[Contract] = None
        self.account: Optional[Account] = None
        
        if self.enabled:
            self._initialize_web3()

    def _initialize_web3(self):
        """Initialize Web3 connection and contracts"""
        try:
            self.w3 = Web3(Web3.HTTPProvider(self.rpc_url))
            
            if not self.w3.is_connected():
                logger.error("Failed to connect to Celo RPC")
                self.enabled = False
                return
            
            logger.info(f"Connected to Celo: {self.rpc_url}")
            
            # Load account from private key
            if self.private_key:
                self.account = Account.from_key(self.private_key)
                logger.info(f"Loaded account: {self.account.address}")
            
            # Initialize contracts
            if self.agent_wallet_address:
                self.agent_wallet = self.w3.eth.contract(
                    address=Web3.to_checksum_address(self.agent_wallet_address),
                    abi=AGENT_WALLET_ABI,
                )
                logger.info(f"Agent wallet loaded: {self.agent_wallet_address}")
            
            if self.prediction_contract_address:
                self.prediction_contract = self.w3.eth.contract(
                    address=Web3.to_checksum_address(self.prediction_contract_address),
                    abi=PREDICTION_CONTRACT_ABI,
                )
                logger.info(f"Prediction contract loaded: {self.prediction_contract_address}")
                
        except Exception as e:
            logger.error(f"Blockchain initialization failed: {e}")
            self.enabled = False

    def generate_prediction_id(
        self, match_id: str, timestamp: int
    ) -> str:
        """Generate prediction ID (keccak256 hash)"""
        if not self.w3:
            # Fallback for when blockchain is disabled
            import hashlib
            data = f"{match_id}{timestamp}".encode()
            return "0x" + hashlib.sha256(data).hexdigest()
        
        return self.w3.keccak(
            text=f"{match_id}{timestamp}"
        ).hex()

    def generate_match_id(
        self, league: str, home_team: str, away_team: str, date: str
    ) -> str:
        """Generate match ID (keccak256 hash)"""
        if not self.w3:
            import hashlib
            data = f"{league}{home_team}{away_team}{date}".encode()
            return "0x" + hashlib.sha256(data).hexdigest()
        
        return self.w3.keccak(
            text=f"{league}{home_team}{away_team}{date}"
        ).hex()

    def submit_prediction(
        self,
        home_team: str,
        away_team: str,
        league: str,
        prediction: str,  # "HOME_WIN", "DRAW", "AWAY_WIN"
        confidence: float,  # 0.0 - 1.0
        match_date: int,  # Unix timestamp
    ) -> PredictionResult:
        """
        Submit prediction on-chain via agent wallet.
        
        Args:
            home_team: Home team name
            away_team: Away team name
            league: League code (EPL, LaLiga, etc.)
            prediction: "HOME_WIN", "DRAW", or "AWAY_WIN"
            confidence: Confidence score 0.0-1.0
            match_date: Unix timestamp of match
            
        Returns:
            PredictionResult with tx_hash or error
        """
        if not self.enabled or not self.agent_wallet or not self.account:
            return PredictionResult(
                success=False,
                error="Blockchain not enabled or not configured"
            )
        
        try:
            # Convert prediction to uint8
            prediction_map = {"HOME_WIN": 0, "DRAW": 1, "AWAY_WIN": 2}
            pred_value = prediction_map.get(prediction, 0)
            
            # Convert confidence to uint256 (0-10000)
            confidence_int = int(confidence * 10000)
            
            # Generate IDs
            timestamp = int(self.w3.eth.get_block("latest")["timestamp"])
            match_id = self.generate_match_id(league, home_team, away_team, str(match_date))
            prediction_id = self.generate_prediction_id(match_id, timestamp)
            
            # Convert hex strings to bytes32 for ABI compatibility
            match_id_bytes = bytes.fromhex(match_id.lstrip("0x").zfill(64))
            prediction_id_bytes = bytes.fromhex(prediction_id.lstrip("0x").zfill(64))

            # Build transaction
            tx = self.agent_wallet.functions.submitPrediction(
                prediction_id_bytes,  # _predictionId (bytes32)
                match_id_bytes,       # _matchId (bytes32)
                home_team,
                away_team,
                league,
                pred_value,
                confidence_int,
                match_date,
            ).build_transaction({
                "from": self.account.address,
                "nonce": self.w3.eth.get_transaction_count(self.account.address),
                "gas": 500000,
                "gasPrice": self.w3.to_wei("0.1", "gwei"),
                "chainId": self.w3.eth.chain_id,
            })
            
            # Sign and send
            signed_tx = self.w3.eth.account.sign_transaction(tx, self.private_key)
            raw_tx = getattr(signed_tx, "rawTransaction", None) or getattr(signed_tx, "raw_transaction", None)
            if raw_tx is None:
                raise AttributeError("SignedTransaction missing raw transaction bytes")
            tx_hash = self.w3.eth.send_raw_transaction(raw_tx)
            
            # Wait for receipt
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)
            
            if receipt["status"] == 1:
                logger.info(f"Prediction submitted: {tx_hash.hex()}")
                return PredictionResult(
                    success=True,
                    tx_hash=tx_hash.hex(),
                    prediction_id=prediction_id,
                )
            else:
                logger.error(f"Transaction failed: {tx_hash.hex()}")
                return PredictionResult(
                    success=False,
                    error=f"Transaction failed: {tx_hash.hex()}"
                )
                
        except Exception as e:
            logger.error(f"Failed to submit prediction: {e}")
            return PredictionResult(
                success=False,
                error=str(e)
            )

    def get_prediction(self, prediction_id: str) -> Optional[Dict[str, Any]]:
        """Get prediction data from chain"""
        if not self.enabled or not self.prediction_contract:
            return None
        
        try:
            pred = self.prediction_contract.functions.getPrediction(
                prediction_id
            ).call()
            
            return {
                "predictionId": pred[0],
                "matchId": pred[1],
                "agent": pred[2],
                "homeTeam": pred[3],
                "awayTeam": pred[4],
                "league": pred[5],
                "prediction": ["HOME_WIN", "DRAW", "AWAY_WIN"][pred[6]],
                "confidence": pred[7] / 10000,  # Convert back to 0-1
                "timestamp": pred[8],
                "matchDate": pred[9],
                "resolved": pred[10],
                "outcome": pred[11],
                "stakeAmount": pred[12],
            }
        except Exception as e:
            logger.error(f"Failed to get prediction: {e}")
            return None

    def resolve_prediction(
        self,
        prediction_id: str,
        actual_outcome: str,  # "HOME_WIN", "DRAW", "AWAY_WIN"
    ) -> Optional[str]:
        """
        Resolve prediction on-chain via the prediction contract.

        Returns:
            tx_hash (hex str) on success, or None on failure
        """
        if not self.enabled or not self.prediction_contract or not self.account:
            return None

        outcome_map = {"HOME_WIN": 0, "DRAW": 1, "AWAY_WIN": 2}
        outcome_uint8 = outcome_map.get(actual_outcome)
        if outcome_uint8 is None:
            logger.error("Unknown outcome label: %s", actual_outcome)
            return None

        # Convert prediction_id string -> bytes32
        pred_id_bytes = prediction_id.encode("utf-8")[:32].ljust(32, b"\x00")

        import time
        for attempt in range(1, 4):
            try:
                nonce = self.w3.eth.get_transaction_count(self.account.address, "pending")
                tx = self.prediction_contract.functions.resolvePrediction(
                    pred_id_bytes,
                    outcome_uint8,
                ).build_transaction({
                    "from": self.account.address,
                    "nonce": nonce,
                    "gas": 300_000,
                    "gasPrice": self.w3.eth.gas_price,
                    "chainId": self.w3.eth.chain_id,
                })
                signed = self.w3.eth.account.sign_transaction(tx, self.private_key)
                tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
                receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)
                if receipt["status"] == 1:
                    logger.info("On-chain resolve SUCCESS: %s", tx_hash.hex())
                    return tx_hash.hex()
                else:
                    logger.warning("On-chain resolve REVERTED: %s", tx_hash.hex())
                    return None
            except Exception as e:
                logger.warning("Resolve attempt %d/3 failed: %s", attempt, e)
                if attempt < 3:
                    time.sleep(2 ** attempt)
        return None

    def get_agent_accuracy(self) -> Optional[float]:
        """Get agent accuracy from chain (0-1)"""

        if not self.enabled or not self.prediction_contract:
            return None
        
        try:
            accuracy = self.prediction_contract.functions.getAgentAccuracy().call()
            return accuracy / 10000  # Convert to 0-1
        except Exception as e:
            logger.error(f"Failed to get accuracy: {e}")
            return None

    def is_backend_authorized(self, address: str) -> bool:
        """Check if backend address is authorized"""
        if not self.enabled or not self.agent_wallet:
            return False
        
        try:
            return self.agent_wallet.functions.isAuthorized(
                Web3.to_checksum_address(address)
            ).call()
        except Exception as e:
            logger.error(f"Failed to check authorization: {e}")
            return False

    def get_connection_status(self) -> Dict[str, Any]:
        """Get current blockchain connection status"""
        return {
            "enabled": self.enabled,
            "connected": self.w3.is_connected() if self.w3 else False,
            "chain_id": self.w3.eth.chain_id if self.w3 else None,
            "account": self.account.address if self.account else None,
            "agent_wallet": self.agent_wallet_address,
            "prediction_contract": self.prediction_contract_address,
            "agent_id": self.agent_id,
        }
